name: "Build and publish site"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Build static site
        run: |
          nix build .#site -j auto
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: result
